feat: hostd v2 changes
SiaFoundation/web pull request #677
Opened 2024-08-09 17:01 UTC by alexfreska

2024-08-09 17:01 UTC, alexfreska commented
* **#677** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/677?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alexfreska and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-12 15:57 UTC, n8maninger requested changes
![Screenshot 2024-08-12 at 8 57 22 AM](https://github.com/user-attachments/assets/7c50b21f-73c2-4330-a519-ce2d9fc0a478)

2024-08-14 17:33 UTC, alexfreska commented
@n8maninger I addressed the 3 bits of feedback left on the preview.

2024-08-14 18:23 UTC, n8maninger approved these changes

2024-08-14 18:54 UTC, merged